### ISSUE TITLE
TD boot hang

### ISSUE THREAD

**Issue by ruomengh** [canonical/tdx#106]
I made some changes to the TD kernel cmdline (adding ima_policy=tcb) and installed some applications on the TD, then shutdown it down and boot it again. Below messages happened frequently and TD boot just hang.

qemu-system-x86_64: virtio: bogus descriptor or out of resources
qemu-system-x86_64: virtio: zero sized buffers are not allowed

The qemu process is as below. 
/usr/bin/qemu-system-x86_64 -accel kvm -name process=tdxvm,debug-threads=on -m 16G -vga none -monitor pty -nodefaults -drive file=/home/ruomeng/images/tdx-2404.qcow2,if=virtio,format=qcow2 -monitor telnet:127.0.0.1:9141,server,nowait -bios /usr/share/qemu/OVMF.fd -object ''\''{"qom-type":"tdx-guest","id":"tdx","quote-generation-socket":{"type":"vsock","cid":"1","port":"4050"}}'\''' -cpu host,-kvm-steal-time,pmu=off,tsc-freq=1000000000 -machine q35,hpet=off,kernel_irqchip=split,confidential-guest-support=tdx -device virtio-net-pci,netdev=mynet0 -netdev user,id=mynet0,net=10.0.2.0/24,dhcpstart=10.0.2.15,hostfwd=tcp::10140-:22 -smp 4 -chardev stdio,id=mux,mux=on,logfile=/tmp/vm_log_2024-05-11T0725.log -device virtio-serial,romfile= -device virtconsole,chardev=mux -monitor chardev:mux -serial chardev:mux -nographic

**Comment by fanchen2** [comment]
I failed to reproduce this issue with ima_policy=tcb in guest kernel cmdline and above qemu command, do you have more details about how to reproduce?

**Comment by ruomengh** [comment]
I cannot reproduce the issue either after upgrading TDX module to the latest version. I'll close the issue for now.
