### ISSUE TITLE
Out of the blue, I started getting the following error when trying to create a TDX guest

### ISSUE THREAD

**Issue by fidencio** [canonical/tdx#114]
When it happens, this is the log that I get from the script provided to start a TD VM.
```
qemu-system-x86_64: -accel kvm: get_tdx_capabilities: KVM_TDX_CAPABILITIES failed: Inappropriate ioctl for device
qemu-system-x86_64: -accel kvm: failed to initialize kvm: Inappropriate ioctl for device
```

**Comment by fidencio** [comment]
No, not even a reboot it can be recovered.

**Comment by hector-cao** [comment]
Hello, could you provide the version of the kernel and qemu  ? and also the dmesg output. Thanks !

**Comment by fidencio** [comment]
kernel: 6.8.0-1001-intel
qemu: QEMU emulator version 8.2.2 (Debian 1:8.2.2+ds-0ubuntu1~tdx1.202405212105~ubuntu24.04.1)
dmesg: https://gist.github.com/fidencio/043ea89f57f5cfd9732bba519e0c7527

**Comment by hector-cao** [comment]
The version of qemu you are using is coming from our development repository (8.2.2), the released version is 8.2.1. I think that you are using the outdated repository, could you please update your local tdx repository to HEAD or to 2.0 release tag and run the setup-tdx-host.sh again ?

**Comment by fidencio** [comment]
The system now hangs during the boot.

**Comment by hector-cao** [comment]
Sorry to hear that, could you provide more details on where it hangs ? possibly providing a screen picture ?

**Comment by fidencio** [comment]
![image](https://github.com/canonical/tdx/assets/112762/16eb5274-0127-4702-8157-43df913d06db)

But, please, let's not spend much time on this one.  Let me do this:
* I will restart with a fresh installation
* I will make sure to use the 2.0 tag
* **IF** it happens again, we debug the issue.
