### ISSUE TITLE
About 2M hugepage

### ISSUE THREAD

**Issue by ruomengh** [canonical/tdx#118]
Could anyone share the status and the plan of supporting transparent hugepage for TDX? 

Thanks in advance!

**Comment by fanchen2** [comment]
KVM TDX: TDP MMU: large page support is already supported in this 24.04 release, do you mean this feature?

**Comment by ruomengh** [comment]
Yes, I mean transparent hugepage for TD. Any additional parameters are required to use it?

**Comment by fanchen2** [comment]
Yes, we included this patchset https://lore.kernel.org/all/cover.1708933624.git.isaku.yamahata@intel.com/#r
It is enabled by default, but please pay attention to the release note, guest memory need to be 2M aligned, or it will not be enabled, no additional para needed.

**Comment by ruomengh** [comment]
Thanks for the information!
