### ISSUE TITLE
Customize TDX host and TD guest kernel

### ISSUE THREAD

**Issue by Icegrave0391** [canonical/tdx#124]
Hi, I would like to ask some questions about host/guest kernel customization. 

1. **Host kernel/KVM**

From the `noble-24.04` branch, the host OS is Ubuntu 24.04.
> 4.1 Install Ubuntu 24.04 Server Image
Download and install [Ubuntu 24.04 server](https://cdimage.ubuntu.com/ubuntu-server/daily-live/pending/noble-live-server-amd64.iso) on the host machine.

In this case, can I update the host kernel with my customized KVM? Which kernel source code should I work on, and what should be the host OS `.config`?

From the Release 2.0:
> The host kernel, known as -intel, is based on 6.8 with the TDX v19 KVM patchset. Source [link](https://git.launchpad.net/~canonical-kernel/ubuntu/+source/linux-intel/+git/noble/log/?h=main).

It seems that I can work on the kernel source from the intel 6.8 link? What should be the host kernel configurations?

2. **Guest TD kernel**

For the **Create TD Image**, it is described as:
> In this section, you will create an Ubuntu 24.04-based TD image from scratch or convert an existing VM image into a TD image. This can be performed on any Ubuntu 22.04 or newer system - an Intel TDX-specific environment is not required.

In this case, instead of using the default `ubuntu-24.04-server-cloudimg-amd64.img`, can I use a `Ubuntu 22.04` image?
Moreover, after creating the `.qcow2` disk, can I arbitrarily update the TD guest kernel by compiling my own version (e.g., linux 6.6)?

**Comment by hector-cao** [comment]
Hello, for the host kernel customization, you can read : https://github.com/canonical/tdx/issues/113
For the guest, the image should not be a problem itself, the kernel is important, so if you use a 22.04 image with an appropriate kernel, it should be ok.

**Comment by Icegrave0391** [comment]
> Hello, for the host kernel customization, you can read : #113 For the guest, the image should not be a problem itself, the kernel is important, so if you use a 22.04 image with an appropriate kernel, it should be ok.

Thanks for the reply @hector-cao ! For the guest kernel, is there any specific `.config` I should follow? I tried to use Linux 6.6.0 (even with Ubuntu 24.04), and here are the TDX-related configs:

```
CONFIG_X86_X2APIC=y
CONFIG_INTEL_TDX_GUEST=y
CONFIG_TDX_GUEST_DRIVER=y
CONFIG_SGX=y
```

However, after executing `run-td.sh`, my host cannot ssh into the guest (it seems that the boot procedure hangs). 
In this case, is there any specific kernel config I should enable, or is there any way to diagnose the problem?

**Comment by hector-cao** [comment]
First thing you can do is to use the `tdvirsh` tool to run a normal VM with your image to check if the image boot fine
```
cd guest-tools
XML_TEMPLATE=$PWD/regular_vm.xml.template TD_IMG=<path_to_your_image> ./tdvirsh new
```

**Comment by hector-cao** [comment]
For the guest kernel config, it depends on the kernel version but for 6.6, this config should be enough:

```
CONFIG_INTEL_TDX_GUEST=y
CONFIG_TDX_GUEST_DRIVER=y
```

**Comment by Icegrave0391** [comment]
> First thing you can do is to use the `tdvirsh` tool to run a normal VM with your image to check if the image boot fine
> 
> ```
> cd guest-tools
> XML_TEMPLATE=$PWD/regular_vm.xml.template TD_IMG=<path_to_your_image> ./tdvirsh new
> ```

Thanks for the suggestion! I tested two different guest kernels: (a) a customized linux-6.6.0 (built upon `make defconfig` and TDX guest-related configs), and (b) Ubuntu 24.04's default kernel 6.8.0-x-generic.

* It seems that the `tdvirsh` cannot even run my normal linux6.6.0:

```bash
sdp@sdp:~/tdx/guest-tools$ ./tdvirsh list
Id   Name                                                      State
-------------------------------------------------------------------------
1    tdvirsh-regular_vm-90adb23c-11df-465d-b5f5-8e2e9b739562   running (ssh:43495, cid:3)
```

When I try to ssh into the guest, it hangs. However, my normal KVM and qemu script can successfully boot the guest.
```bash
sdp@sdp:~/tdx/guest-tools$ ssh -v -p 43495 root@localhost
OpenSSH_9.6p1 Ubuntu-3ubuntu13, OpenSSL 3.0.13 30 Jan 2024
debug1: Reading configuration data /home/sdp/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Connecting to localhost [127.0.0.1] port 43495.
debug1: Connection established.
debug1: identity file /home/sdp/.ssh/id_rsa type -1
debug1: identity file /home/sdp/.ssh/id_rsa-cert type -1
debug1: identity file /home/sdp/.ssh/id_ecdsa type -1
debug1: identity file /home/sdp/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/sdp/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/sdp/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/sdp/.ssh/id_ed25519 type -1
debug1: identity file /home/sdp/.ssh/id_ed25519-cert type -1
debug1: identity file /home/sdp/.ssh/id_ed25519_sk type -1
debug1: identity file /home/sdp/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/sdp/.ssh/id_xmss type -1
debug1: identity file /home/sdp/.ssh/id_xmss-cert type -1
debug1: identity file /home/sdp/.ssh/id_dsa type -1
debug1: identity file /home/sdp/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.6p1 Ubuntu-3ubuntu13
```

When I update the `/etc/default/grub` to use linux-6.8-x-generic, everything goes well again.

I highly suspect there are some configurations I haven't enabled (such as some extra modules). Given that my kernel is customized, I cannot use the script `setup-tdx-guest.sh` to install all extra modules. 

In this case, are there any recommended ways to test? (i.e., how to show the guest `dmesg`)

**Comment by Icegrave0391** [comment]
Thanks for your suggestions. I resolved the problem :)
