### ISSUE TITLE
Package name change - Ubuntu 23.10

### ISSUE THREAD

**Issue by philipcking** [canonical/tdx#127]
I was unable to run the setup-tdx-host.sh script successfully since it tries to fetch a package with a bad name

As delivered, the script tries to install 'linux-image-intel' but the real package name is 'linux-image-intel-opt'
 (see https://packages.ubuntu.com/search?suite=mantic&section=all&arch=any&keywords=linux-image-intel&searchon=names)
 
 By adjusting the package name in the script, I was able to work around this issue....
 
 # the kernel flavour/type we want to use
KERNEL_TYPE=linux-image-intel-opt

Now the script completes successfully and I'm off to set up TDX in the BIOS (next step).

**Comment by hector-cao** [comment]
Hello, which branch/tag are you using ?

**Comment by bktan8** [comment]
I spoke with @philipcking about this.  He was running Mantic, but using the Noble setup-tdx-host.sh script.  Recommended him to start fresh with Noble host and all related scripts.  He agreed.  So we can close this.
