### ISSUE TITLE
Wrong url to the server iso in project README 

### ISSUE THREAD

**Issue by mmilews** [canonical/tdx#130]
![image](https://github.com/canonical/tdx/assets/71321949/278b1f3c-a941-4d63-bffc-2b41856d5e1d)

**Comment by mmilews** [comment]
Perhaps the url should point to https://cdimage.ubuntu.com/ubuntu-server/noble/daily-live/pending/noble-live-server-amd64.iso

**Comment by bktan8** [comment]
Fix in #136
