### ISSUE TITLE
faster mirror for cloud-images.ubuntu.com ?

### ISSUE THREAD

**Issue by matti** [canonical/tdx#154]
when running `/tdx/guest-tools/image/create-td-image.sh` I often see slow download speeds like 1.21MB/s (from a datancenter 1GB/s connection)

Is there some faster mirror and could the script use it automatically?

**Comment by hector-cao** [comment]
Hello; i m wondering if we can find a faster mirror for all user locations; one thing we could do is to offer to possibility to users to set the mirror to use for downloading this image
