### ISSUE TITLE
Failed to install libtdx-attest-dev

### ISSUE THREAD

**Issue by qzheng527** [canonical/tdx#159]
I followed the doc and successfully created a TD guest image.
I booted it in a TD host server and checked the output as below.
```
root@tdx-guest:~# dmesg | grep -i tdx
[    0.000000] tdx: Guest detected
[    0.397124] process: using TDX aware idle routine
[    0.491737] Memory Encryption Features active: Intel TDX
[    3.862191] systemd[1]: Detected confidential virtualization tdx.
[    3.867223] systemd[1]: Hostname set to <tdx-guest>.
```

But I failed install the attestation tools in the guest by following [doc](https://github.com/canonical/tdx?tab=readme-ov-file#83-setup-intel-tiber-trust-services-cli-inside-td). It showed below error.
```
root@tdx-guest:~/tdx/attestation# ./setup-attestation-guest.sh
....
Unattended-Upgrade::Allow-downgrade "true";
Hit:1 http://security.ubuntu.com/ubuntu noble-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu noble InRelease
Hit:3 http://archive.ubuntu.com/ubuntu noble-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu noble-backports InRelease
Hit:5 https://ppa.launchpadcontent.net/kobuk-team/tdx-release/ubuntu noble InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libtdx-attest-dev
E: Unable to locate package trustauthority-cli
```
Can anyone help me out?
Thanks.

**Comment by mmisono** [comment]
I had the same issue. We need to update the PPA: https://github.com/canonical/tdx/pull/158

**Comment by hector-cao** [comment]
@qzheng527 Hello, apologies, we did a mistake while doing our MR on separating the attestation packages to an other PPA; we should not have removed the packages in the current PPA too early that breaks current users experience, i just copied back these packages into the current PPA tdx-release

**Comment by hector-cao** [comment]
FYI @mmisono

**Comment by qzheng527** [comment]
> @qzheng527 Hello, apologies, we did a mistake while doing our MR on separating the attestation packages to an other PPA; we should not have removed the packages in the current PPA too early that breaks current users experience, i just copied back these packages into the current PPA tdx-release

@hector-cao 
Stil the same error when trying install **libtdx-attest-dev**.
Do I need wait for some time for this?

**Comment by aneessahib** [comment]
@hector-cao  One of our internal releases are blocked on this. Can you please expedite the fix in the current PPA. Thanks.

**Comment by amathew3** [comment]
The issue resolved only for `libtdx-attest-dev` and `trustauthority-cli` still failing.
```
sudo apt install trustauthority-cli
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package trustauthority-cli
```
`trustauthority-cli` is not seen in tdx-release ppa, libtdx-attest-dev is now available in tdx-release PPA
```
awk '$1 == "Package:" { if (a[$2]++ == 0) print $2; }' /var/lib/apt/lists/*kobuk-team_tdx-release*|grep trust

intel@intel-SYS-221H-TNR:/etc/apt/sources.list.d$ awk '$1 == "Package:" { if (a[$2]++ == 0) print $2; }' /var/lib/apt/lists/*kobuk-team_tdx-release*|grep libtdx-attest-dev
libtdx-attest-dev
```

**Comment by hector-cao** [comment]
@amathew3 @aneessahib yes, we are still missing `trustauthority-cli`; i m working on fixing it, apologies

**Comment by hector-cao** [comment]
@amathew3 @aneessahib I should be ok now, the `trustauthority-cli` is available again in the PPA

**Comment by jinengandhi-intel** [comment]
Getting the following error now:

```
sudo apt install trustauthority-cli
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
 
The following packages have unmet dependencies:
trustauthority-cli : Depends: libtdx-attest1 (>= 1.21) but it is not going to be installed
E: Unable to correct problems, you have held broken packages
```

**Comment by qzheng527** [comment]
Same error here now:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 trustauthority-cli : Depends: libtdx-attest1 (>= 1.21) but 1.20-0ubuntu1 is to be installed
E: Unable to correct problems, you have held broken packages.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
```

**Comment by hector-cao** [comment]
@qzheng527 @jinengandhi-intel I should be ok now; please give it a try again

**Comment by qzheng527** [comment]
> @qzheng527 @jinengandhi-intel I should be ok now; please give it a try again

@hector-cao Yes, it works! Many thanks!
