### ISSUE TITLE
make a new release

### ISSUE THREAD

**Issue by matti** [canonical/tdx#166]
Latest release is from 10.5.2024, shouldn't there be a newer release since main has a lot of fixes?

Anyway, when starting a new install, the README says to checkout from a release - should I use the 2 month old release or main?

**Comment by hector-cao** [comment]
@matti Hello, we plan to do a new release in August;  this release will cover the tdx repo (setup scripts) and qemu, libvirt + attestation (dcap 1.21 + ITA 1.5); for the moment, these components are still in the development PPA and even if you use the main of the TDX release; it will not give you access to these components; is there any thing in the new release you are especially interested in ?

**Comment by matti** [comment]
nope, just a question now on what should I use in #155 issue after reinstall: main or the release tag from may

**Comment by hector-cao** [comment]
@matti Could we close this issue ?

**Comment by matti** [comment]
yes
