### ISSUE TITLE
QEMU TD disk access slow

### ISSUE THREAD

**Issue by matti** [canonical/tdx#169]
My QEMU TD takes about 10s to login with ssh. Then all disk access is extremely slow, here I'm extracting a docker image to the disk at ~400 K/s

<img width="1140" alt="image" src="https://github.com/user-attachments/assets/7e2a2baf-8781-478b-a62b-7cdb4857a259">

Would virsh be faster?

**Comment by hector-cao** [comment]
Hello @matti ; this might be due to an outdated firmware version; please check : https://github.com/canonical/tdx/issues/128

**Comment by matti** [comment]
Thank you again @hector-cao - updated BIOS and now running

```
TDX module: attributes 0x0, vendor_id 0x8086, major_version 1, minor_version 5, build_date 20240129, build_num 698
```
performance improved:

![image](https://github.com/user-attachments/assets/a14ac423-26e4-46a5-bbf0-225dfa17207b)
