### ISSUE TITLE
shell script conventions: double brackets

### ISSUE THREAD

**Issue by matti** [canonical/tdx#173]
All scripts should use double brackets and not single brackets:

In Bash scripting, the single bracket `[` and double bracket `[[` notations are used for conditional expressions, but they have some differences in behavior and capabilities. Let's explore the differences between the two forms of the `if` statement you provided:

### Single Bracket `[ ]`
```bash
if [ -f ${SCRIPT_DIR}/../../setup-tdx-config ]; then
    source ${SCRIPT_DIR}/../../setup-tdx-config
fi
```
- **Syntax**: `[ condition ]` is a test command, which is an older and more portable syntax.
- **Features**:
  - It is POSIX-compliant and available in all Bourne-like shells (`sh`, `bash`, `dash`, `ksh`, etc.).
  - It requires spaces around the brackets and between operators and operands.
  - It has more limited functionality compared to double brackets.
  - Special characters (like `*`, `?`, etc.) need to be escaped or quoted to avoid globbing.

### Double Bracket `[[ ]]`
```bash
if [[ -f ${SCRIPT_DIR}/../../setup-tdx-config ]]; then
    source ${SCRIPT_DIR}/../../setup-tdx-config
fi
```
- **Syntax**: `[[ condition ]]` is a Bash-specific keyword that provides more advanced functionality.
- **Features**:
  - It is not POSIX-compliant and is available only in `bash`, `ksh`, and `zsh`.
  - It does not require spaces around the brackets and allows more complex expressions.
  - It supports additional operators (like `=~` for regex matching) and logical operators (`&&`, `||`) directly within the brackets.
  - It performs better with strings containing spaces, special characters, or globs without the need for escaping or quoting.

### Key Differences
1. **Portability**: 
   - `[ ]` is more portable and will work in any POSIX-compliant shell.
   - `[[ ]]` is specific to `bash` and similar shells.

2. **Functionality**:
   - `[[ ]]` supports more complex expressions and additional operators.
   - `[[ ]]` handles strings and special characters more gracefully.

### Practical Impact in Your Script
In the context of your script:
```bash
if [ -f ${SCRIPT_DIR}/../../setup-tdx-config ]; then
    source ${SCRIPT_DIR}/../../setup-tdx-config
fi

if [[ -f ${SCRIPT_DIR}/../../setup-tdx-config ]]; then
    source ${SCRIPT_DIR}/../../setup-tdx-config
fi
```
Both forms will correctly check for the existence of the file `${SCRIPT_DIR}/../../setup-tdx-config` and source it if it exists. However, the choice between `[ ]` and `[[ ]]` depends on the shell you are using and whether you need the extra capabilities provided by `[[ ]]`.

### Recommendation
- If you need maximum portability and are only performing simple file checks, use `[ ]`.
- If you are using `bash` or a similar shell and might need more complex expressions or safer handling of special characters, use `[[ ]]`.

Given the provided script and assuming you're using `bash`, either option will work fine. If you might expand the script with more complex conditions later, `[[ ]]` might be a better choice.

**Comment by hector-cao** [comment]
Thanks, i will take this into account for my next requests; closing
