### ISSUE TITLE
shell script conventions: set -eEuo pipefail

### ISSUE THREAD

**Issue by matti** [canonical/tdx#174]
following #170, all scripts should have `set -eEuo pipefail`

Including the line `set -eEuo pipefail` at the beginning of a bash script helps ensure that the script runs safely and fails fast if it encounters errors. Let's break down what each option does:

1. **`-e`**: Exit immediately if a command exits with a non-zero status.
   - This helps in stopping the script as soon as an error occurs, preventing further commands from being executed and potentially causing more issues.

2. **`-E`**: Ensures that any trap on `ERR` is inherited by shell functions, command substitutions, and commands executed in a subshell environment.
   - This makes sure that error handling defined with `trap` is consistently applied throughout the script, including within functions and subshells.

3. **`-u`**: Treat unset variables and parameters as an error when performing parameter expansion.
   - This helps catch typos and unset variables early, which can prevent unexpected behavior and difficult-to-debug issues.

4. **`-o pipefail`**: If set, the return value of a pipeline is the value of the last (rightmost) command to exit with a non-zero status, or zero if all commands exit successfully.
   - This ensures that errors in any part of a pipeline are not ignored. For example, in the command `cmd1 | cmd2 | cmd3`, if `cmd1` fails, the entire pipeline will fail, rather than just the last command's exit status being considered.

By combining these options, you make your bash scripts more robust and easier to debug. Here’s a summary of the benefits:

- **Fail Fast**: The script stops execution on errors, reducing the chance of cascading failures.
- **Consistent Error Handling**: Traps are inherited, making error handling more consistent.
- **Catch Unset Variables**: Unset variables are treated as errors, helping to catch bugs early.
- **Proper Pipeline Error Handling**: Errors in pipelines are not ignored, ensuring more reliable script execution.

Adding `set -eEuo pipefail` is a good practice for writing safer and more reliable bash scripts.

**Comment by hector-cao** [comment]
Thanks, i will take this into account for my next requests; closing
