### ISSUE TITLE
shell script conventions: parameter expansion

### ISSUE THREAD

**Issue by matti** [canonical/tdx#175]
### Basic Variable Expansion

In Bash, both of these lines will work the same way:

```bash
info "(Check logfile for more details $LOGFILE)"
```

```bash
info "(Check logfile for more details ${LOGFILE})"
```

In this context:

- `$LOGFILE` will be replaced by the value of the `LOGFILE` variable.
- `${LOGFILE}` does the same thing but is a bit clearer, especially in more complex cases.

### When to Use Braces (`${}`)

Using braces around the variable name, like `${LOGFILE}`, can be particularly useful when:

1. **Concatenating Variables**: To clearly delineate where the variable name ends, especially when combining it with other text or variables.
   ```bash
   info "Logfile path is ${LOGFILE}/suffix"
   ```

2. **Avoiding Ambiguity**: If you’re working with variable names that might be close to other text or variables.
   ```bash
   echo "The log file is located at ${LOGFILE}_suffix"
   ```

### Default Values with `${VAR:-defaultvalue}`

You can also use a default value with `${VAR:-defaultvalue}`. This provides a way to specify a default if `VAR` is unset or null.

- **`${VAR:-defaultvalue}`**: Expands to the value of `VAR` if it is set and not null; otherwise, it expands to `defaultvalue`.

Here's an example:

```bash
# Assume LOGFILE is not set or is empty
info "Logfile path is ${LOGFILE:-/default/path/to/logfile}"
```

In this case:

- If `LOGFILE` is set and has a non-null value, `info` will output that value.
- If `LOGFILE` is unset or empty, `info` will use `/default/path/to/logfile` as the default value.

Using `${LOGFILE:-/default/path}` can be especially useful in scripts where you want to ensure that a variable has a fallback value, preventing errors or unintended behavior if the variable is not set.

**Comment by hector-cao** [comment]
Thanks i will take it into account for my current MR and next ones, closing
