### ISSUE TITLE
Create an image based on Ubuntu 22.04

### ISSUE THREAD

**Issue by VicoinDub** [canonical/tdx#180]
Can I use the tools provided in this repository to create an image based on Ubuntu 22.04?

**Comment by bktan8** [comment]
@VicoinDub - you want to build a 22.04 TD guest?

**Comment by VicoinDub** [comment]
Yes,
how do I use create-td-image.sh? I tried changing the download address to:
`export OFFICIAL_UBUNTU_IMAGE="https://cloud-images.ubuntu.com/jammy/current/"
export CLOUD_IMG="jammy-server-cloudimg-amd64.img"`,then `sudo ./create-td-image.sh`

but encountered the following issue:
SUCCESS: Verify the checksum for Ubuntu cloud image.
SUCCESS: Copy the jammy-server-cloudimg-amd64.img => /tmp/tdx-guest-tmp.qcow2
Image resized.
[   0.0] Examining the guest ...
virt-customize: error: libguestfs error: /usr/bin/supermin exited with 
error status 1.
To see full error messages you may need to enable debugging.
Do:
  export LIBGUESTFS_DEBUG=1 LIBGUESTFS_TRACE=1
and run the command again.  For further information, read:
  http://libguestfs.org/guestfs-faq.1.html#debugging-libguestfs
You can also run 'libguestfs-test-tool' and post the *complete* output
into a bug report or message to the libguestfs mailing list.

If reporting bugs, run virt-customize with debugging enabled and include 
the complete output:

  virt-customize -v -x [...]
ERROR: Failed to resize guest image to 50G

**Comment by VicoinDub** [comment]
it seems like #133

**Comment by bktan8** [comment]
BTW - 22.04 guest is not supported and untested.  You should use 24.04 for best comparability.
