### ISSUE TITLE
tdx_att_get_report failed return TDX_ATTEST_ERROR_DEVICE_FAILURE in initramfs stage

### ISSUE THREAD

**Issue by qzheng527** [canonical/tdx#183]
The TDX RA is working fine in the guest VM rootfs env. 
I want to do this RA in initramfs as well.
I updated the initramfs of the guest VM and packaged the TDX RA binary into it.
But the initramfs RA failed in **tdx_att_get_report** step, returning **TDX_ATTEST_ERROR_DEVICE_FAILURE**.
After booting into rootfs, the same RA works fine.
Can anyone give some clue for this issue?

BTW, the similar init RA works fine in the same maching before with redhat OS. 
In that OS, the qemu could work with parameter "quote-generation-service=vsock:2:4050" while the current qemu in ubuntu 24.04 can not support this parameter. I don't know it it is relevent.

**Comment by qzheng527** [comment]
After adding tdx_module probe in initramfs, the issue is gone.

**Comment by hector-cao** [comment]
@qzheng527 Hello; interesting, 
can you tell me more about Intel RA and how you set it up in initramfs, if you can share your initramfs; i can do a quick test at my side

About the quote-generation-service=vsock:2:4050; our QEMU renamed it into `quote-generation-socket`; please see : https://github.com/canonical/tdx/pull/179/files#diff-ab3fc6d9372af75dfc07f1a51663cd86c4301cf20e1c8034f027456d53844a51

**Comment by qzheng527** [comment]
@hector-cao I basically followed the steps in CCZoo [tdx-encrypted-tdvm-image](https://github.com/intel/confidential-computing-zoo/tree/main/cczoo/tdx-encrypted-tdvm-image/initramfs-hooks/ubuntu) to update the initramfs with TDX RA function.
