### ISSUE TITLE
Lack of connectivity between TD and QGSD

### ISSUE THREAD

**Issue by marchrap** [canonical/tdx#187]
Hi, I followed the steps to configure my machine and successfully booted a TD. However, when trying to attest the TD, I get the following output: 
```
tdx@tdx:/usr/share/doc/libtdx-attest-dev/examples$ sudo ./test_tdx_attest  
                TDX report data

 00000000: 59 a8 28 5a ba 21 f4 6e b0 6a a0 b9 3f fe 88 4c
 00000010: d6 33 d6 0b 9e 7b d5 25 d1 80 e5 70 0b f7 0c 65
 00000020: 9f 34 bf 5a 55 b3 c8 06 1d 68 bf 5d 67 48 a9 3d
 00000030: 7b 80 48 1a fb 1d 3f cc 9d 25 3c a9 1c 49 0e bc

Wrote TD Report to report.dat

Failed to get the quote
```

I checked the logs for QGSD and PCCS, and nothing suggests that the TD has requested a quote:
```
Aug 04 20:54:38 sdp systemd[1]: Starting qgsd.service - Intel(R) TD Quoting Generation Service...
Aug 04 20:54:38 sdp systemd[1]: Started qgsd.service - Intel(R) TD Quoting Generation Service.
Aug 04 20:54:38 sdp qgsd[3476]: Added signal handler
Aug 04 20:54:38 sdp qgsd[3476]: About to create QgsServer with num_thread = 4
Aug 04 20:54:38 sdp qgsd[3476]: About to start main loop
```
```
Aug 04 20:30:08 sdp systemd[1]: Started pccs.service - Provisioning Certificate Caching Service (PCCS).
Aug 04 20:30:11 sdp node[3442]: 2024-08-04 20:30:11.259 [info]: HTTPS Server is running on: https://localhost:8081
```

I used the QEMU start script from the repo. The other commands perform as expected. 

Do you have any idea what might be causing the problem? It looks like there is some problem with the communication sock, but I can't figure out what exactly. Thanks in advance for the help.

**Comment by hector-cao** [comment]
@marchrap can you provide the log in the guest when you get the failure ? Also, which branch of the tdx repo did you use ?

**Comment by marchrap** [comment]
@hector-cao Which logs do you mean? Could you please provide the command?

I am on the `noble-24.04` branch, commit `5e4a70877028bd73fa02b218eb5a502f96d05f6e` (`Dev improve log (#171)`).

**Comment by hector-cao** [comment]
latest logs lines (happening around the time when you issue the quote generation command) from journactl would be fine

**Comment by marchrap** [comment]
Here's the output:
```
Aug 07 08:56:21 tdx-guest sudo[1288]:     root : TTY=pts/0 ; PWD=/usr/share/doc/libtdx-attest-dev/examples ; USER=root ; COMMAND=./test_tdx_attest
Aug 07 08:56:21 tdx-guest sudo[1288]: pam_unix(sudo:session): session opened for user root(uid=0) by root(uid=0)
Aug 07 08:56:21 tdx-guest test_tdx_attest[1290]: libtdx_attest: cannot parse sock port - fallback to tdvmcall mode.
Aug 07 08:56:21 tdx-guest sudo[1288]: pam_unix(sudo:session): session closed for user root
```

**Comment by hector-cao** [comment]
Can you provide the contents of `/etc/tdx-attest.conf` in the guest ?

**Comment by marchrap** [comment]
There is nothing inside.

**Comment by hector-cao** [comment]
Weird. could you please put this content to this file : ` port =4050`  and try again ?

**Comment by marchrap** [comment]
@hector-cao Great that solved the problem; thanks!
