### ISSUE TITLE
Can not fetch TDX key number in Ubuntu 24.04

### ISSUE THREAD

**Issue by LeiZhou-97** [canonical/tdx#189]
In Ubuntu23.10, I can get the tdx key number from the misc controller. But I cannot get the number in Ubuntu24.04. Do you have any concerns about why this feature is being dropped or just a bug?
```bash
cat /sys/fs/cgroup/misc.capacity
tdx 32
```

**Comment by hector-cao** [comment]
@LeiZhou-97 For 24.04 which is a LTS, we dropped some features we considered not essential from 23.10. If you want to get the number of private keys for TDX you can refer to https://github.com/canonical/tdx/blob/7abc5f7c78131d0006ad32960e678f627eb1fa76/system-report.sh#L58
