### ISSUE TITLE
Improve the system-report.sh 

### ISSUE THREAD

**Issue by BFuhry** [canonical/tdx#192]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I very much like the `system-report.sh` script that was added to the repo.

I have a few related suggestions:
1. While executing `system-report.sh` on a fresh Ubuntu installation, the “set_msr_result_string” function leads to multiple `rdmsr: command not found` entries, because the `msr-tools` package is not installed by default. You might want to check the presence of the command at the beginning of the script and exit if not present.
2. For the `set_msr_result_string` function in `system-report.sh`, you also might want to look at https://cc-enabling.trustedservices.intel.com/intel-tdx-enabling-guide/05/host_os_setup/#check-intel-tdx-enablement at which we provide details about the MSRs you are reading. I especially consider “HW_ENCRYPT_ENABLE” a bit misleading. For the number of key, there is also no expectation of having a number > 32. 
3. You might consider to integrate the `check-production.sh` script into `system-report.sh`. This would make `system-report.sh` more standalone. Currently, `check-production.sh` is only used in step 8.1, but the following code change would be enough to replace the command in step 8.1 with  `./system-report.sh | grep -i 'production status'`.

    ```
    diff --git a/attestation/check-production.sh b/attestation/check-production.sh
    index 04f1e16..86e7529 100755
    --- a/attestation/check-production.sh
    +++ b/attestation/check-production.sh
    @@ -47,7 +47,7 @@ fi
    
    echo "CPU: ${CPU_GEN}"
    if [ "${PROD}" = "0" ]; then
    -    echo "Production"
    +    echo "Production status: production"
    else
    -    echo "Pre-production"
    +    echo "Production status: pre-production"
    fi
    ```
4. The file `/var/log/mpa_registration.log` is not present if the corresponding package is not installed. As a result, the script currently returns the error `tail: cannot open '/var/log/mpa_registration.log' for reading: No such file or directory` instead of just not not returning the log. I'd propose the following change:

    ```
    diff --git a/system-report.sh b/system-report.sh
    index aa97629..88d5a8e 100755
    --- a/system-report.sh
    +++ b/system-report.sh
    @@ -122,7 +122,7 @@ print_section "QGSD service status" "${result}"
     result=$(systemctl status pccs 2>&1)
     print_section "PCCS service status" "${result}"
    
    -result=$(tail -n 30 /var/log/mpa_registration.log)
    +result=$(tail -n 30 /var/log/mpa_registration.log 2>/dev/null)
     print_section "MPA registration logs (last 30 lines)" "${result}"
    
     printf "<======== COPY ABOVE HERE ========>\n"
    ```

**Additional context**
N/A

**System report**
N/A

**Comment by hector-cao** [comment]
Thanks Benny, 
```
For the number of key, there is also no expectation of having a number > 32.
```
32 might be a wrong number but i recall reading somewhere that the number of private keys must be more than 16. I will try to find this material again

**Comment by hector-cao** [comment]
@BFuhry I did not get your change suggestion on the `check-production.sh` script; could you please elaborate a little more ?

**Comment by BFuhry** [comment]
> 32 might be a wrong number but i recall reading somewhere that the number of private keys must be more than 16. I will try to find this material again

In general, the minimal and maximal number of keys usable for TDs depends on the processor at hand. In particular, the minimum depends on the maximum number of bits available for MKTME Keys, because the TD keys are a subset of the MKTME keys. To keep this generic, you can just use > 0 and note that it depends on what was configured in the BIOS.

> @BFuhry I did not get your change suggestion on the `check-production.sh` script; could you please elaborate a little more ?

The main suggestion: get rid of  `check-production.sh` and just integrate its functionality directly into `system-report.sh`. This is, however, a bit more complex, because the README currently and rightfully tells customers to check for a production CPU in step 8.1. I provided you a diff for  `check-production.sh` that you could use before integrating the content into `system-report.sh`. Then, you can replace `sudo ./setup-tdx-host.sh` by `sudo ./system-report.sh | grep -i 'production status'` in step 8.1. As a result, `system-report.sh` will not rely on another script and customers still have a way to figure out if the CPU is production or pre-production,

**Comment by BFuhry** [comment]
> @BFuhry
> 
> 1. Ok for the keys
> 2. I think we should separate the reporting script (system-report.sh) and README instruction asking user to run check-production.sh. They are 2 separate things; serving 2 different purposes. I will take your suggestion to integrate the check-production.sh source code into system-report.sh to make the latter more standalone,

Regarding 2: sure, I just wanted to get rid of code duplication. `check-production.sh.` does anyhow no longer (only) do what the name suggest. In theory, you could also just replace the commands in 8.1 with:
```
apt install -y msr-tools &> /dev/null
modprobe msr
[ "$(sudo rdmsr 0xce -f 27:27)" -eq 1 ] && echo "Pre-production" || echo "Production"
```
In this case, you do no longer need the script.

**Comment by hector-cao** [comment]
@BFuhry Please check out the merge request https://github.com/canonical/tdx/pull/193  and leave feedback directly there

**Comment by hector-cao** [comment]
> > @BFuhry
> > 
> > 1. Ok for the keys
> > 2. I think we should separate the reporting script (system-report.sh) and README instruction asking user to run check-production.sh. They are 2 separate things; serving 2 different purposes. I will take your suggestion to integrate the check-production.sh source code into system-report.sh to make the latter more standalone,
> 
> Regarding 2: sure, I just wanted to get rid of code duplication. `check-production.sh.` does anyhow no longer (only) do what the name suggest. In theory, you could also just replace the commands in 8.1 with:
> 
> ```
> apt install -y msr-tools &> /dev/null
> modprobe msr
> [ "$(sudo rdmsr 0xce -f 27:27)" -eq 1 ] && echo "Pre-production" || echo "Production"
> ```
> 
> In this case, you do no longer need the script.

I still want the script; i dont see any reason to move the script contents to the README

**Comment by BFuhry** [comment]
> > > @BFuhry
> > > 
> > > 1. Ok for the keys
> > > 2. I think we should separate the reporting script (system-report.sh) and README instruction asking user to run check-production.sh. They are 2 separate things; serving 2 different purposes. I will take your suggestion to integrate the check-production.sh source code into system-report.sh to make the latter more standalone,
> > 
> > 
> > Regarding 2: sure, I just wanted to get rid of code duplication. `check-production.sh.` does anyhow no longer (only) do what the name suggest. In theory, you could also just replace the commands in 8.1 with:
> > ```
> > apt install -y msr-tools &> /dev/null
> > modprobe msr
> > [ "$(sudo rdmsr 0xce -f 27:27)" -eq 1 ] && echo "Pre-production" || echo "Production"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > In this case, you do no longer need the script.
> 
> I still want the script; i dont see any reason to move the script contents to the README

Sure, absolutely your decision. Personally, I don't like to add scripts as an indirection if it just replaces 3 commands by 1.
