### ISSUE TITLE
Attestation token received, now what?

### ISSUE THREAD

**Issue by matti** [canonical/tdx#195]
In the README.md

<img width="1588" alt="image" src="https://github.com/user-attachments/assets/6db7ee8b-cc3e-425a-affb-fbcf2478f808">

How do continue from here, from where do I fetch a public key to verify the string that I have on my screen?

**Comment by bktan8** [comment]
@matti - Please see step 4-5 on https://docs.trustauthority.intel.com/main/articles/concept-patterns.html?tabs=passport.

**Comment by hector-cao** [comment]
Closing since there is no possible fix for this issue,

**Comment by bktan8** [comment]
@hector-cao - Just want to be clear that this isn't a bug that needs fixing.  After a token is received from ITA, it can be used by a 3rd-party to verify authenticity of the TD and unlock service.

**Comment by matti** [comment]
and I just want to be clear that this repo README should point to those places
