### ISSUE TITLE
Can one nest TD vm's?

### ISSUE THREAD

**Issue by matti** [canonical/tdx#200]
Can I run a TD vm inside of TD vm?

**Comment by matti** [comment]
https://github.com/AMDESE/AMDSEV/issues/169

**Comment by hector-cao** [comment]
Hello @matti ; nested virtualization is not supported right now by TDX

**Comment by hector-cao** [comment]
Closing since there no possible fix for this issue in the short term

**Comment by diegoara96** [comment]
Hi @matti ,

We had this same doubt and we saw that the architecture itself does not allow it. What it does allow is to create a normal VM and then inside it using Kata Containers have a secure domain. With this you could have a confidential kubernetes cluster where the atestation also works.
