### ISSUE TITLE
Mention prerequisites

### ISSUE THREAD

**Issue by joshwyant** [canonical/tdx#258]
Readme doesn't mention that create-td-image won't work if you don't have the following apt packages installed:

`guestfs-tools virt-manager genisoimage`

**Comment by frenchwr** [comment]
Hello, I suspect that you did not run the script with `sudo` as [mentioned in the README](https://github.com/canonical/tdx?tab=readme-ov-file#51-create-a-new-td-image). One of the first things the script does is [to install these dependencies](https://github.com/canonical/tdx/blob/noble-24.04/guest-tools/image/create-td-image.sh#L309), but they will not install without `sudo`. Let us know if that helps!

**Comment by joshwyant** [comment]
IIRC, I got this error when running with sudo, but it might have been the result of previously not running sudo or something, which put everything in a bad state?

**Comment by hector-cao** [comment]
@joshwyant Thanks for your feedback, i created a MR to enforce the root requirement for this script, it will make things simpler and avoid users to run into this kind of weird state,  at your side, i believe that you are unblocked for this reported issue, am i right ?
