### ISSUE TITLE
How to debug TD guest using GDB?

### ISSUE THREAD

**Issue by Hsy-Intel** [canonical/tdx#266]
**Describe the support request**

How to debug TD guest using GDB?

**System report**
Please run the `system-report.sh` script (located in the root directory of this repo) on your host system and copy the output below.

**Comment by hector-cao** [comment]
@Hsy-Intel Do you mean debug the VMM on the host (qemu process ?)

**Comment by Hsy-Intel** [comment]
> @Hsy-Intel Do you mean debug the VMM on the host (qemu process ?)

Yes.

**Comment by fanchen2** [comment]
This function is unavailable.
The reason of this is, the TDX is designed to provide a security VM to the end user, the memory content & vCPU state protection is base of such security, but debugging capability relies on access the VM’s memory content and vCPU state, so it doesn’t have such feature now.

**Comment by BFuhry** [comment]
Intel TDX offers various ways to debug from inside a Trust Domain or from outside a Trust Domain. Details can be found in the chapter "Debug and Profiling Architecture" of the "Intel® Trust Domain Extensions (Intel® TDX) Module Base Architecture Specification" (https://cdrdv2.intel.com/v1/dl/getContent/733575)
