### ISSUE TITLE
How to install TDX on rocky9.4(kernel=5.14)

### ISSUE THREAD

**Issue by justin-better** [canonical/tdx#267]
**Is your feature request related to a problem? Please describe.**
My working environment is limited to Rocky9.4 and cannot use ubuntu24.04. I tried to change the ubuntu script to support rocky, but the kernel patch could not be successfully integrated.

**Describe the solution you'd like**
The setup_*.sh can run successful on Rocky9.4 with kernel 5.14, and TDX can be installed successful on Rocky9.4.

**Comment by bktan8** [comment]
Hello @justin-better - This project requires Ubuntu 24.04 as the base OS.  There a CentOS version of TDX that you can try.  It's much closer to Rocky.  https://sig.centos.org/virt/tdx/.
