### ISSUE TITLE
Check image presence and change default path in run_td.sh

### ISSUE THREAD

**Issue by BFuhry** [canonical/tdx#28]
The script `run_td.sh` does not check if the image is present that should be used to start a TD.
The script will just silently fail if the image is not present.

Additionally, changing the default path from `ubuntu-23.10-td.qcow2` to `image/tdx-guest-ubuntu-23.10.qcow2` would match the default path if customer strictly follows the project's README. The `TD_IMG=<path_to_td_qcow2_image>` part could even be removed from `TD_IMG=<path_to_td_qcow2_image> ./run_td.sh` in the README making the start of a TD easier.

**Comment by petitfou** [comment]
@BFuhry Thanks ! I created a PR, if you have sometime, please check if it fixes the issue

**Comment by BFuhry** [comment]
I can confirm that your solution will prevent a silent fail. Using a wrong image path, I receive the following:
```
The script failed...
qemu-system-x86_64: -drive file=test,if=none,id=virtio-disk0: Could not open 'test': No such file or directory
```

I can imagine that your solution will catch various errors and thus should be helpful overall.
However, I would propose to also add an explicit check for a wrong path of the image and print an explicit error message.
