### ISSUE TITLE
Default Root Password Vulnerability in TD VM Creation

### ISSUE THREAD

**Issue by anjalirai-intel** [canonical/tdx#297]
**Describe the bug**
when a new TD VM is created with a different user and password, it is still possible to log in to the TD VM using the root user with the default password 123456

**To Reproduce**
Create a new TD VM using the following command:

sudo ./create-td-image.sh -o tdx_guest_ubuntu.qcow2 -u intel -p intel@test -n intelvm

Attempt to log in to the newly created TD VM using the specified user credentials:
Username: intel
Password: intel@test

Additionally, attempt to log in to the TD VM using the root user with the default password:
Username: root
Password: 123456

**Observed Behavior:**
The TD VM allows login with the specified user credentials (intel / intel@test).
The TD VM also allows login with the root user using the default password (123456).

**Expected Behavior:**
The TD VM should only allow login with the specified user credentials.
The root user should not be accessible with the default password (123456).
.

**Comment by bktan8** [comment]
Hi @anjalirai-intel - The default root password is made available for convenience and testing purposes, not intended for production.  The owner is welcome to change it.
