### ISSUE TITLE
tdx_kvm qemu-system_x86_64 don’t support TDVM memory format “memory-backend-memfd-private”

### ISSUE THREAD

**Issue by hageng123** [canonical/tdx#30]
Hi:
with current TDX kernel 6.5.0.1003,
qemu-system_x86_64 don’t support TDVM memory format “memory-backend-memfd-private”.
please see the attached picture
<img width="738" alt="Screenshot 2024-02-05 at 10 26 43" src="https://github.com/canonical/tdx/assets/158980266/0eccd5aa-120e-4b6d-a8cf-4f505fd724c3">
<img width="761" alt="Screenshot 2024-02-05 at 10 27 03" src="https://github.com/canonical/tdx/assets/158980266/38fe0ad0-fb17-4856-8462-57b2c3762377">
<img width="1034" alt="Screenshot 2024-02-05 at 10 27 14" src="https://github.com/canonical/tdx/assets/158980266/c4c30b54-5b9f-4619-8696-74f4994f8bbe">

**Comment by fanchen2** [comment]
You are using the old version qemu command to boot TDVM, please refer to the qemu para in https://github.com/canonical/tdx/blob/main/guest-tools/run_td.sh.

**Comment by hageng123** [comment]
Thanks your quick response.
Yes, I tried to launch TD VM successfully with your linked file.
but failure script is from Intel:
https://github.com/intel/tdx-tools/blob/tdx-1.5/start-qemu.sh.
so intel need update its script, right??

**Comment by fanchen2** [comment]
https://github.com/intel/tdx-tools/blob/tdx-1.5/start-qemu.sh is released by the old MVP team, the kernel they released at that time is 6.2. Update or not, it depends which kernel/qemu version they plan to match.

**Comment by hageng123** [comment]
Hi fanchen2:
got it. Thanks. you can close this issue.

**Comment by fanchen2** [comment]
Could you help to close? I have no permission to close, thank you

**Comment by hageng123** [comment]
close this
