### ISSUE TITLE
Unable to create multiple domains using run_td.sh/run_td_virsh .sh

### ISSUE THREAD

**Issue by amathew3** [canonical/tdx#39]
Current run_td.sh kills the existing VM create a new one. 
run_td_virsh.sh also destroying the existing domain and create a fresh one.

here is the console output.
```
 TD_IMG=/home/sdp/tdx/guest-tools/image/tdx-guest.qcow2 ./run_td.sh
Cleanup, kill TD vm PID: 46537
TD VM, PID: 47194, SSH : ssh -p 10022 root@localhost
```
Is there a plan to add support for creating multiple domains using run_td.sh/run_td_virsh.sh

**Comment by amathew3** [comment]
Hi @frenchwr,  Yes,  enhancing the libvirt script(`run_td_virsh.sh`) is a perfect option.
Thanks.

**Comment by frenchwr** [comment]
Hi, this is now available in `td_virsh_tool.sh` in the `main` branch. Instructions can be found [here](https://github.com/canonical/tdx?tab=readme-ov-file#boot-td-guest-with-virsh-libvirt). Let us know what you think.
