### ISSUE TITLE
RTMR[1] does not change when changing kernel param

### ISSUE THREAD

**Issue by YurkoWasHere** [canonical/tdx#40]
Reading the docs in https://github.com/intel/tdx-tools/tree/tdx-mid-stream/attestation/pytdxmeasure  direct boot seems to indicate that RTMR[1] should include cmdline passed to kernel

However i get the same RTMR[1] regardless of the cmdline passed. Am i missing something?

```
RTMR[1]:
82ef32cc6e1a4346d1cc2ccf23617e78
75934ddaa58db1a6ef39e91c317e1aa1
a5a2e3db37b661e3042b0ba040357785
```

```
[    0.000000] Command line: console=ttyS0 test1 initrd=initrd

[    0.000000] Command line: console=ttyS0 test1 initrd=initrd
 
[    0.000000] Command line: console=ttyS0 test=2 initrd=initrd'
```

my qemu boot is as follows

```
qemu-system-x86_64 \
-nographic \
-kernel vmlinuz.intel \
-append "$(cat vmlinuz.cmdline)" \
-initrd ./initramfs.intel.cpio.gz \
-cpu host -object tdx-guest,id=tdx  \
-accel kvm -m 80G -smp 16  \
-device vhost-vsock-pci,guest-cid=5 \
-machine q35,hpet=off,kernel_irqchip=split,memory-encryption=tdx,memory-backend=ram1  \
-object memory-backend-ram,id=ram1,size=80G,private=on  \
-name td,process=td,debug-threads=on \
-bios /usr/share/ovmf/OVMF.fd  \
-pidfile current.pid \
-nodefaults 
```

**Comment by sathyaintel** [comment]
I think it is because bootloader/firmware is not measuring the cmdline options. I think we have to rely to Linux bootstub to do it. We have merged the related support in v6.9. Can you try with tip tree or upcoming v6.9-rc1 kernel ? Following are the related fixes.

https://git.kernel.org/pub/scm/linux/kernel/git/efi/efi.git/commit/?h=efi-next-for-v6.9&id=3e0b0f880e9e8f39f433dc6734cff035f9de2c8e
https://git.kernel.org/pub/scm/linux/kernel/git/efi/efi.git/commit/?h=efi-next-for-v6.9&id=0bbe5b0ea97aaaea6387bab89919a8654b07df27
https://git.kernel.org/pub/scm/linux/kernel/git/efi/efi.git/commit/?h=efi-next-for-v6.9&id=ac93cbfc2a2c8e9641a4b49cd1e7b9d34f935e1a
https://git.kernel.org/pub/scm/linux/kernel/git/efi/efi.git/commit/?h=efi-next-for-v6.9&id=d228814b1913444dfdd9a25519ed7b38a19653e2

**Comment by ruomengh** [comment]
Will these patches mentioned in the last comment be in TDX packages of Ubuntu 24.04? They are important for measurement of TDX RTMR.

**Comment by bktan8** [comment]
These patches will be in Ubuntu 24.04.  https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2060130

**Comment by ruomengh** [comment]
> These patches will be in Ubuntu 24.04. https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2060130

@bktan8 Thanks! Do you have ETA of the TDX packages for Ubuntu 24.04?

**Comment by YurkoWasHere** [comment]
I compiled and booted kernel
`Linux (none) 6.9.0-rc4 #1 SMP Mon Apr 15 04:55:54 PDT 2024 x86_64 x86_64 x86_64 GNU/Linux`

RTME[1] still is static when cmdline changes.

**Comment by bktan8** [comment]
> > These patches will be in Ubuntu 24.04. https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2060130
> 
> @bktan8 Thanks! Do you have ETA of the TDX packages for Ubuntu 24.04?

@ruomengh - you can test it now in our pre-release branch.  https://github.com/canonical/tdx/tree/noble-24.04

**Comment by bktan8** [comment]
> I compiled and booted kernel `Linux (none) 6.9.0-rc4 #1 SMP Mon Apr 15 04:55:54 PDT 2024 x86_64 x86_64 x86_64 GNU/Linux`
> 
> RTMR[1] still is static when cmdline changes.
> 
> (To be clear, this is GUEST os not HOST os)

@YurkoWasHere - can you please try pre-release TDX on Ubuntu 24.04 branch?  https://github.com/canonical/tdx/tree/noble-24.04

**Comment by hyuan3** [comment]
> I compiled and booted kernel `Linux (none) 6.9.0-rc4 #1 SMP Mon Apr 15 04:55:54 PDT 2024 x86_64 x86_64 x86_64 GNU/Linux`
> 
> RTMR[1] still is static when cmdline changes.
> 
> (To be clear, this is GUEST os not HOST os)

RTMR interface is not added in Ubuntu 24.04 yet because new ABI is under discussion in community (Please refer to https://lore.kernel.org/lkml/20240128212532.2754325-1-sameo@rivosinc.com/). So suppose the user space tool can't read out the RTMR registers in Ubuntu 24.04 guest.

**Comment by YurkoWasHere** [comment]
Is this for the host of guest?

**Comment by sathyaintel** [comment]
Cmdline measurement is stored in RTMR[2]. Please check the index 2.

**Comment by fanchen2** [comment]
Hi @YurkoWasHere, can I know which guest kernel you tested on? 6.8.0-1001-intel or 6.8.0-22-generic/6.8.0-31-generic ?

**Comment by YurkoWasHere** [comment]
6.8.0-1001-intel

I am currently compiling 6.9-rc4 because i could not compile nvidia drivers against 1001-intel supplied headers.
