### ISSUE TITLE
Unable to Lunch Guest TDX VM

### ISSUE THREAD

**Issue by AndySync** [canonical/tdx#46]
/home/administrator/tdx/guest-tools# TD_IMG=/home/administrator/tdx/guest-tools/image/tdx-guest-ubuntu-23.10.qcow2 ./run_td_virsh.sh
Wait for VM to shutdown ...
error: Failed to define domain from td_guest.xml
error: unsupported configuration: INTEL TDX launch security is not supported with this QEMU binary

root@dnpemr3:/home/administrator/tdx/guest-tools# TD_IMG=/home/administrator/tdx/guest-tools/image/tdx-guest-ubuntu-23.10.qcow2 ./run_td.sh
qemu-system-x86_64: -object tdx-guest,id=tdx: Parameter 'qom-type' does not accept value 'tdx-guest'
The script failed...

**Comment by fanchen2** [comment]
Can you check your QEMU version?
Below is the qemu version this repo released for TDX:
root@farrah:~# qemu-system-x86_64 --version
QEMU emulator version 8.0.4 (Debian 1:8.0.4+dfsg-1ubuntu3**+tdx1.0**)
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers

**Comment by AndySync** [comment]
Apt upgrade – has upgrade the QEMU version so I had to downgrade it with build host script , now it works

Had to revert back.

FROM
QEMU emulator version 8.0.4 (Debian 1:8.0.4+dfsg-1ubuntu3.23.10.3)
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developer

TO
QEMU emulator version 8.0.4 (Debian 1:8.0.4+dfsg-1ubuntu3+tdx1.0)
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers

Best Regards,
Andy

Datacenter & AI Cloud Solution Architect
Technology Office & Customer Innovation Labs | Sales & Marketing Group
***@***.***<https://www.intel.com/content/www/us/en/homepage.html>

**Comment by AndySync** [comment]
Closing the issue
