### ISSUE TITLE
How do I compile a specific VM?

### ISSUE THREAD

**Issue by DiWangShePi** [canonical/tdx#61]
I saw in the repository's instructions that the preparation part of creating an Ubuntu 23.10 VM can be done in any Ubuntu 22.04 and above operating system, I was wondering if I could create an Ubuntu 22.04 VM?
If so, what should I do? Intel/tdx-tools seems to have been achieved.

**Comment by Icegrave0391** [comment]
Hi @DiWangShePi ,

Did you figure that problem out? 

I also want to customize my TD guest VM (by using Ubuntu 22.04 with my own kernel source code). Executing the default scripts seems to not work.

**Comment by DiWangShePi** [comment]
Hi @Icegrave0391

Unfortunately, I haven't solved this issue yet. If you have any progress later, I would really like you to share it through this issue.

Best.

**Comment by hector-cao** [comment]
@DiWangShePi Hello, 22.04 is not supported as a TD guest, you can use 22.04 image but have to use a more recent kernel (the kernel version for 22.04 is 5.15). Do you have any specific reason to not move to 24.04 ?

**Comment by hector-cao** [comment]
We do not deliver a tdx guest kernel for Jammy. You can try to build one your self, more details can be found in this issue : https://github.com/canonical/tdx/issues/113

**Comment by Icegrave0391** [comment]
Hi @DiWangShePi ,

I successfully booted a guest TD kernel version of linux-6.6, while using Ubuntu 24.04 image.

Here are some suggestions from my experience:

1. Use the default Ubuntu 24.04 image, but downgrade your guest kernel. 

2. Add an early `printk` support as the boot CMDLINE to diagnose what's going wrong.

For `run_td.sh`, I prefer to avoid the `-daemonize` option to boot the guest, as it omits the boot messages. Instead, for debugging purposes, you could add the option `-serial mon: studio` to interact with your TD guest via the terminal.

I would also add the following grub configuration in `/etc/default/grub.d/50-cloudimg-settings.cfg`:

```bash
GRUB_CMDLINE_LINUX_DEFAULT="console=tty1 console=ttyS0 earlyprintk=serial
```

The `earlyprintk=serial` really helps to test some weird cases in which the guest is failed during booting.

You could refer to this issue for more details: #124.
