### ISSUE TITLE
Boot TDVM with td_virsh_tool.sh, write some data on VM, poweroff and use td_virsh_tool.sh to boot TDVM again, data is gone

### ISSUE THREAD

**Issue by fanchen2** [canonical/tdx#68]
Reproduce steps:
**farrah@emr-111144:~/tdx/guest-tools$ ./td_virsh_tool.sh**
Domain td_guest-18fae13e-282b-4a39-8734-0cd500234622 running with vsock CID: 3, ssh -p 38383 root@localhost
**farrah@emr-111144:~/tdx/guest-tools$ ssh -p 38383 root@localhost**

Last login: Thu Apr 18 21:04:18 2024 from 10.0.2.2
**root@tdx-guest:~# touch mytesting0419**

root@tdx-guest:~# ls
mytesting0419  test

**root@tdx-guest:~# poweroff**

Connection to localhost closed.
**farrah@emr-111144:~/tdx/guest-tools$ ./td_virsh_tool.sh**
Domain td_guest-6b55841e-8bd5-436c-86e2-e17e9b80dedf running with vsock CID: 3, ssh -p 44575 root@localhost
farrah@emr-111144:~/tdx/guest-tools$ ssh -p 44575 root@localhost

Last login: Thu Apr 18 21:04:18 2024 from 10.0.2.2
**root@tdx-guest:~# ls**
test

**Comment by fanchen2** [comment]
The workaround is use virsh to start the same VM again, and use " ./td_virsh_tool.sh --list" to get new host_forward for guest ssh.

**Comment by frenchwr** [comment]
Improved docs around this issue in https://github.com/canonical/tdx/pull/82, and an improved version of the script will be offered soon.
