### ISSUE TITLE
"Obtain an PCS API key" is vague

### ISSUE THREAD

**Issue by matti** [canonical/tdx#78]
README says "Obtain an [Intel PCS API key](https://api.portal.trustedservices.intel.com/provisioning-certification). This is needed to configure the PCCS service in the next step. Specifically, you should subscribe to the Provisioning Certification Service."

When one clicks that link there is no matches for PCS or PCSS.

So I click "Get PCK Certificate/s" which opens up this and I have now idea what to click next:

<img width="706" alt="image" src="https://github.com/canonical/tdx/assets/3893/b4b85ef7-8f66-4f57-9725-a3ae257520e9">

**Comment by matti** [comment]
Ignoring all of the above, there is a "subscribe" button on the bottom of the page. It then shows "Your subscriptions" and two keys "Primary key" and "Secondary key"

so I assume that these are the API keys and I can just use either or?

**Comment by mythi** [comment]
> so I assume that these are the API keys and I can just use either or?

yes, correct
