### ISSUE TITLE
I'm having trouble with the "TDX is Enabled on HOST" section

### ISSUE THREAD

**Issue by ggr432** [canonical/tdx#83]
I'm having trouble with the "TDX is Enabled on HOST" section, does anyone know how to fix it? thanks.

jason@jason-C2184:~/Desktop$ uname -a
Linux jason-C2184 6.8.0-1001-intel #7-Ubuntu SMP PREEMPT_DYNAMIC Thu Apr 11 09:56:59 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

/jason@jason-C2184:~/Desktop$ sudo dmesg | grep -i tdx
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-6.8.0-1001-intel root=UUID=ba635a53-f42e-4d68-87fe-5a79fcfe4a52 ro kvm_intel.tdx=1 nohibernate quiet splash vt.handoff=7
[    2.435064] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-6.8.0-1001-intel root=UUID=ba635a53-f42e-4d68-87fe-5a79fcfe4a52 ro kvm_intel.tdx=1 nohibernate quiet splash vt.handoff=7
[    5.118752] virt/tdx: BIOS enabled: private KeyID range [1, 128)
[    5.118754] virt/tdx: Disable ACPI S3. Turn off TDX in the BIOS to use ACPI S3.
[   14.036730] virt/tdx: SEAMCALL (0x0000000000000022) failed: 0xc000050500000000
[   14.036735] virt/tdx: RCX 0x0000000000000000 RDX 0x9100000100000008 R08 0x0000000000000000
[   14.036737] virt/tdx: R09 0x0000000000000000 R10 0x0000000000000000 R11 0x0000000000000000
[   14.036738] virt/tdx: module initialization failed (-5)
[   14.036739] kvm_intel: Failed to initialize TDX module.

**Comment by fanchen2** [comment]
Which platform are you in? SPR/EMR?

**Comment by ggr432** [comment]
> Which platform are you in? SPR/EMR?

SPR Platform 
CPU: Intel(R) Xeon(R) Platinum 8473C

**Comment by fanchen2** [comment]
Did you updated TDX module to 1.5? The default tdx module in SPR bios is 1.0, the new kernel cannot work with tdx module 1.0.
Recommend TDX_1.5.05.46.698 UPLR2 or TDX_1.5.06.00.744 UPLR2.

**Comment by ggr432** [comment]
I installed it according to the script below:
Should the script have updated TDX module to 1.5?

OS: Ubuntu 24.04
4. Setup TDX Host
cd tdx
sudo ./setup-tdx-host.sh
reboot

**Comment by fanchen2** [comment]
No, all the scripts and guidance here can only update software and TDVF, but for tdx module, we have to do it ourselves.

**Comment by fanchen2** [comment]
If you are intel partners or customers, you can ask intel support team for support.
If you are the customers of other vendors using intel CPU, you can ask your vendors for support.
If you are intel inside, welcome to ping Bun(bun.k.tan@intel.com) or me(farrah.chen@intel.com)

**Comment by hector-cao** [comment]
@ggr432 as @fanchen2 mentioned, the required firmware version is `TDX_1.5.05.46.698 UPLR1` or `TDX_1.5.06.00.744 UPLR2`. To see how you can get the system updated, please reach out to hardware vendor for assistance. Does that make sense ?

**Comment by BFuhry** [comment]
@ggr432 Please not that "regular" SPR CPUs do not support Intel TDX - independent of the TDX Module you are using.

**Comment by marcelamelara** [comment]
Hello! I've run into this same error when trying to enable TDX on an Emerald Rapids server (Fox Creek Pass). Per your recommendation above, I confirmed that the latest firmware should support TDX 1.5. 

Here's the output of `sudo dmesg | grep -i tdx` after following steps 4.1-4.3 of your Host OS setup on the current tip of the noble-24.04 branch ([a8261b1](https://github.com/canonical/tdx/commit/a8261b15784a5bd9962bbc5af63d27444b8bbb3c)):

```
[    0.000000] Command line: BOOT_IMAGE=/boot/vmlinuz-6.8.0-1004-intel root=UUID=135651d7-8961-4488-ac65-186eef7498f1 ro kvm_intel.tdx=1 nohibernate
[    0.957299] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-6.8.0-1004-intel root=UUID=135651d7-8961-4488-ac65-186eef7498f1 ro kvm_intel.tdx=1 nohibernate
[    1.630945] virt/tdx: BIOS enabled: private KeyID range [32, 64)
[    1.630948] virt/tdx: Disable ACPI S3. Turn off TDX in the BIOS to use ACPI S3.
[   10.444055] virt/tdx: TDX module: attributes 0x0, vendor_id 0x8086, major_version 1, minor_version 5, build_date 20231008, build_num 595
[   10.444059] virt/tdx: CMR: [0x100000, 0x6f800000)
[   10.444061] virt/tdx: CMR: [0x100000000, 0x107a000000)
[   10.444061] virt/tdx: CMR: [0x1080000000, 0x207c000000)
[   10.444062] virt/tdx: CMR: [0x2080000000, 0x307c000000)
[   10.444063] virt/tdx: CMR: [0x3080000000, 0x407c000000)
[   10.774047] virt/tdx: initialization failed: TDMR [0x0, 0x80000000): reserved areas exhausted.
[   10.824954] virt/tdx: module initialization failed (-28)
[   10.824960] kvm_intel: Failed to initialize TDX module.
```

Thank you for any recommendations on how to resolve this!

**Comment by hector-cao** [comment]
Hello, thanks for your feedback, the error you get is different from the one in this issue. if you have a chance to update the tdx module version to TDX_1.5.05.46.698 or later, it can help us on the investigation. In the meantime, please create a new issue
