### ISSUE TITLE
clarify 'verify guest' steps

### ISSUE THREAD

**Issue by mythi** [canonical/tdx#89]
7.2. is not fully accurate:

2. Verify the tdx_guest device exists.

`ls /dev/tdx_guest`

An example output:

`/dev/tdx_guest`

while this is true, `/dev/tdx_guest` is mostly unused so checking that does not verify the core functionality.

Suggesting the following instead:

```
# testreport0=/sys/kernel/config/tsm/report/testreport0
# mkdir $testreport0
# cat $testreport0/provider
tdx_guest
# rmdir $testreport0
```

**Comment by hector-cao** [comment]
@mythi Thanks, good idea, will do

**Comment by mythi** [comment]
> DCAP still uses it, i would say that it is still used, even more than tsm (i dont think that any userspace of guest uses it for now)

DCAP 1.21 (the latest release) defaults to TSM reports. `/dev/tdx_guest` only offers 'get TD report' ioctl which isn't very useful to most use-cases. There are no guest kernels with 'get quote' ioctl supported and the work in this repo should not enable it.

**Comment by hector-cao** [comment]
Thanks. Can you tell in which use-cases `/sys/kernel/config/tsm/report` can be used and  where `ioctl(/dev/tdx_guest, GET_REPORT` cannot be used ?

**Comment by mythi** [comment]
> in which use-cases `/sys/kernel/config/tsm/report` can be used

It can be used to generate TD quotes that can be remotely verified. This is what the rest of the README expects to be working (QGS, PCCS etc).

> where `ioctl(/dev/tdx_guest, GET_REPORT` cannot be used

TD reports are not signed by the QGS so they cannot be used for remote attestation.

**Comment by hector-cao** [comment]
I should miss something, could we generate a quote without generating a report previously ?

**Comment by mythi** [comment]
> I should miss something, could we generate a quote without generating a report previously ?

This is how `/sys/kernel/config/tsm/report` works (while it generates a report internally, user space only gets to see a quote)

**Comment by hector-cao** [comment]
You are right, i took a look at the code, i will do the change, thanks

**Comment by fanchen2** [comment]
@hector-cao FYI, to use configfs-tsm for getting QUOTE, we should use 
`-object '{"qom-type":"tdx-guest","id":"tdx","quote-generation-socket":{"type": "vsock", "cid":"2","port":"4050"}}' `
in QEMU command for TDVM boot, instead of the old `QUOTE_ARGS="-device vhost-vsock-pci,guest-cid=3"`.
And `-object tdx-guest,id=tdx` should be removed together to avoid duplicate.
I thought the DCAP version you plan to release with 24.04 was not updated to use configfs-tsm.

**Comment by ruomengh** [comment]
This question is a follow-up to the previous comment. Which version of QGS and PCCS will be released with 24.04?

**Comment by ruomengh** [comment]
> The current version is 1.20, I see that upstream DCAP has released 1.21 last week, we will bump to this version in the coming weeks

Thanks.  Except for DCAP 1.21, is branch [nobel-24.04](https://github.com/canonical/tdx/tree/noble-24.04) ready to use?

**Comment by mythi** [comment]
> The current version is 1.20,

Where can I see this?  I'm only able to find 1.18.

**Comment by hector-cao** [comment]
https://launchpad.net/~kobuk-team/+archive/ubuntu/tdx?field.series_filter=noble
