### ISSUE TITLE
How to install Intel TDX module (TDX_1.5.05.46.698 UPLR1) to Ubuntu

### ISSUE THREAD

**Issue by ggr432** [canonical/tdx#91]
I obtained TDX_1.5.05.46.698 UPLR1 data from Intel, which contains the following file contents. Can anyone tell me how to install it to Ubuntu 23.10? Thank a lot.

TDX_1.5.05.46_PRODUCTION_SIGN.so
TDX_1.5.05.46_PRODUCTION_SIGN.so.sigstruct
TDX_1.5.05.46_PRODUCTION_SIGN.sig
TDX_1.5.05.46_PRODUCTION_SIGN.spdx
SEAM_1.5.02.00_SEAMLDR_PW_signed.bin
SEAM_1.5.02.00_SEAMLDR_PROD_SIGN.sig
SEAM_1.5.02.00_SEAMLDR_PROD_SIGN.spdx

**Comment by hector-cao** [comment]
```
mkdir -p /boot/efi/EFI/TDX/
cp SEAM_1.5.02.00_SEAMLDR_PW_signed.bin /boot/efi/EFI/TDX/TDX-SEAM_SEAMLDR.bin 
cp TDX_1.5.05.46_PRODUCTION_SIGN.so /boot/efi/EFI/TDX/TDX-SEAM.so 
cp TDX_1.5.05.46_PRODUCTION_SIGN.so.sigstruct /boot/efi/EFI/TDX/TDX-SEAM.so.sigstruct 
```

**Comment by ggr432** [comment]
@hector-cao Thank you very much, I will try it.

**Comment by fu-ju** [comment]
Can I compile and sign the firmware based on the open source TDX code? @hector-cao

**Comment by hector-cao** [comment]
@fu-ju No it is not possible; the firmware must be signed by Intel

**Comment by fu-ju** [comment]
@hector-cao Thank you very much！

**Comment by roshanr95** [comment]
@ggr432 Any tips on how to acquire the TDX module from Intel?
