### ISSUE TITLE
Show package installation status at the beginning of create-td-image.sh

### ISSUE THREAD

**Issue by bktan8** [canonical/tdx#93]
During the first use of create-td-image.sh, it installs a bunch of packages.  The status is being captured in /tmp/logfile.  It would be good to show what's happening on the screen as well so it doesn't give the impression it's hanging, causing the user to wonder and maybe press Ctl-C.

**Comment by hector-cao** [comment]
The thing is, sometimes, lot of logs might mask useful log messages,
