### ISSUE TITLE
Update example configuration to enter Intel PCS API key for pccs configuration

### ISSUE THREAD

**Issue by anjalirai-intel** [canonical/tdx#95]
As per README, step 5 Configure the PCCS service, part of [Setup Intel® SGX Data Center Attestation Primitives (Intel® SGX DCAP) on the Host](https://github.com/canonical/tdx?tab=readme-ov-file#setup-intel-sgx-data-center-attestation-primitives-intel-sgx-dcap-on-the-host)

_In example configuration Intel PCS API key is not set, it is just mentioned `set it later in config/default.json`, it is mandatory to set Intel PCS API Key before going for registration with PCKIDRetrievalTool. In later steps also we don't set this API Key in config/default.json So when user proceeds for next steps which is registration it fails._

**Resolution:**
Either add Intel PCS API Key as part of example configuration or add additional step on updating Intel PCS API key in config/default.json

**Comment by bktan8** [comment]
Resolved in #196
