### ISSUE TITLE
How to verify the attestation's attestation?

### ISSUE THREAD

**Issue by matti** [canonical/tdx#98]
In the README it says that once you get back this:

```console
2024/03/19 23:59:09 [DEBUG] GET https://api.trustauthority.intel.com/appraisal/v1/nonce

Get the vsock port number [4050]

Reply message body is 5030 bytes
2024/03/19 23:59:13 [DEBUG] POST https://api.trustauthority.intel.com/appraisal/v1/attest
Trace Id: U5sA2GNVoAMEPkQ=
eyJhbGciOiJQUzM4NCIsImprdSI6Imh0dHBzOi8vYW1iZXItdGVzdDEtdXNlcjEucHJvamVjdC1hbWJlci1zbWFzLmN
.....
.....
.....
DRctLIeN4MioXztymyK7qsT1p7n7Dh56-HmDQH47MVgrEL_S-wRYDQioEkUvtuA_3pGk
```

It's successful. How? Isn't something missing from the README?

So basically:

1. You log in to a "TD VM" remotely
2. It's not really a TD VM, but it looks like it is, it has /dev/tdx_guest etc.
3. You download the trustauthority-cli
4. You see this kind of stuff that's above
5. But you are in environment which is not TD VM, so you can see whatever the host wants you to see ?

And, when you download something, you write it to disk which is not encrypted (yet?) so the host can just swap your binary ?

My examples are oversimplified, but I hope you understand what I'm after.

**Comment by mythi** [comment]
> My examples are oversimplified, but I hope you understand what I'm after.

Not really. A non-TD VM cannot generate a quote. trustauthority-cli will fail if the evidence you pass is not a valid. I think you also got the concepts a bit mixed. The output from trustauthority-cli is a JWT token but that is not expected to be consumed by the TD VM itself but it's further passed to whatever needs to verify the owner of the token (remote attestation "passport model") and the claims in it.

The VM admin is expected to make the VM image secure (fs encryption or just integrity protected) for real deployments and so that the state of it is reflected in the quote (measured boot etc.). The samples in this repo are not secure by default. With confidential VMs, the VM admin is also different from who starts/stops the VM on the host.

**Comment by matti** [comment]
But how is VM admin able to make the VM image secure? It can not be booted if it's fs encrypted?

So is the expected model to:
1. boot unencrypted vm
2. do attestation
3. and if successful, then decrypt an additional disk with the received key?

**Comment by mythi** [comment]
> But how is VM admin able to make the VM image secure? It can not be booted if it's fs encrypted?

This https://intel.github.io/ccc-linux-guest-hardening-docs/security-spec.html#storage-protection and the full spec. overall gives things to consider when hardening the guest from an untrusted host.

**Comment by hector-cao** [comment]
@mythi Thanks, i found this presentation also very useful : https://lpc.events/event/16/contributions/1260/attachments/932/1950/Secure%20bootloader%20for%20Confidential%20Computing%20-%20LPC.pdf

**Comment by hector-cao** [comment]
@matti Can we consider this issue closed ?

**Comment by matti** [comment]
@mythi okay thanks, that link was very helpful.

So how would one go and implement that LUKS + agent on initrd, is there some actual reference implementation that I can have a look at?

I already run LUKS on my host hardware like everybody else: it just asks the passphrase to decrypt the volume on the console on boot.

**Comment by hector-cao** [comment]
The complete solution will be likely implemented by cloud providers, for example, Azure offers a TDX preview right now with secure boot and full disk encryption features, but they are only using Ubuntu as the guest

**Comment by matti** [comment]
@hector-cao but I have my own tdx hardware here, I want to implement this full disk encryption on that

**Comment by hector-cao** [comment]
Sure, do you have ideas on how you would do the attestation ?

**Comment by hector-cao** [comment]
And I m sorry to say that we do not have yet the design solution and reference implementation for secure boot and FDE with TDX,

**Comment by matti** [comment]
@mythi but isn't this FDE unnecessary? like doesn't the quote already provide enough proof that the vm image is actually the one that got booted?

FDE would still be useful to allow vm to write to disk so that the host could not read the data written, but for my original question it is not required?

But still, how do I verify that quote.dat that it is actually generated from with my provided image and not some other image running in TD?

The README of this repo still stops before this is answered. I understand that technically this falls out of the scope of this repo, but without it I'm not sure whats the use of this either.

I don't really know where to look for this info, it should be linked atleast.

**Comment by ruomengh** [comment]
> @mythi okay thanks, that link was very helpful.
> 
> So how would one go and implement that LUKS + agent on initrd, is there some actual reference implementation that I can have a look at?
> 
> I already run LUKS on my host hardware like everybody else: it just asks the passphrase to decrypt the volume on the console on boot.

@matti You may want to check the FDE reference solution at [full-disk-encryption](https://github.com/cc-api/full-disk-encryption). It introduces a solution with a FDE agent, KBS and image encryption tool and OVMF enroll tool. As preparation, the decryption key is registered to a KBS. When TD boots, FDE agent gets quote and sends it to KBS. After quote verification, the key will be sent back for image decryption.

**Comment by mythi** [comment]
> FDE would still be useful to allow vm to write to disk so that the host could not read the data written, but for my original question it is not required?

Are you referring to "you write it to disk which is not encrypted (yet?) so the host can just swap your binary?". The [hardening doc](https://intel.github.io/ccc-linux-guest-hardening-docs/security-spec.html#virtio-and-shared-memory) implies when encrypting the disk is needed (i.e., when the user cares for the integrity and confidentiality for what gets written to the virtio-blk backed disk). However, there can also be usages when the OS disk is integrity protected and read-only and writes are done to some ram backed tmpdir...

 > But still, how do I verify that quote.dat that it is actually generated from with my provided image and not some other image running in TD?

There are a few ways to do it. TDX quote supports custom fields such as `mrconfigid`, `mrowner`, `mrownerconfig` that QEMU can set (poor documentation still, though). These can then be read from the quote. Alternatively, your VM can be identified through the measure boot eventlog (CCEL). It gives you things like kernel cmdline, kernel, initrd hashes. For example, if your dm-verity protected rootfs has a specific root hash added to the cmdline, you'd be able to check it was your cmdline that was used to boot the VM.

**Comment by arvind5** [comment]
> But still, how do I verify that quote.dat that it is actually generated from with my provided image and not some other image running in TD?

In addition to @mythi's comments, Intel Trust Authority also provides a capability wherein you can upload Attestation policy for your TD in which you can include your TD measurements/attributes. With this when the trustauthority client sends a TD quote to Intel Trust Authority for attestation, the Intel Trust Authority will verify the TD measurements/attributes in the TD quote against the Attestation policy created. And the result of policy verification will be included as a claim in token to let user know whether the policy was matched with the TD quote or not. For more details on attestation policies please refer https://docs.trustauthority.intel.com/main/articles/concept-policies.html
